services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_API_URL=${REACT_APP_API_BASE}
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      engine:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    command: npm run dev

  engine:
    build:
      context: ./engine
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./engine:/app
      - ./backend/uploads:/app/uploads
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  celery_worker:
    build:
      context: ./engine
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - ./engine:/app
      - ./backend/uploads:/app/uploads
    command: celery -A celery_app worker --loglevel=info

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: pgvector/pgvector:pg16
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d intello_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  backend_node_modules:
  postgres_data:
