
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
      - engine
    volumes:
      - ./backend:/app
      - /app/node_modules

  engine:
    build: ./engine
    ports:
      - "8000:8000"
    volumes:
      - ./engine:/app

  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
