FROM python:3.11-slim

WORKDIR /app
#hedha i needed to copy it expelicitly khater didnt work before 
COPY services/credentials/service-account.json service-account.json
#poppler, tesseract + language support
RUN apt-get update && apt-get install -y \
    poppler-utils \
    tesseract-ocr \
    tesseract-ocr-eng \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]